apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd # argo-cdnamespace.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/dhayv/azure-rag-infra
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfheal: true
    syncOptions:
      - CreateNamespace=true

